
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC 15
 */
public class MainWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
	setLocationRelativeTo(null);
	setResizable(false);
	setTitle("Formulario Agencia Viajes");
	MontañaP.setVisible(false);
	PlayaP.setVisible(false);
        txtDestino.setEnabled(false);
        txtDias.setEnabled(false);
        txtPrecioBase.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoP = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboSeleccion = new javax.swing.JComboBox<>();
        MontañaP = new javax.swing.JPanel();
        txtCostoGuia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAlquilerEquipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSeguroPorcentaje = new javax.swing.JTextField();
        PlayaP = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtImpuestoTuristico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDescuentoTuristico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorial = new javax.swing.JTextArea();
        txtDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoP.setBackground(new java.awt.Color(255, 255, 255));
        fondoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(255, 255, 239));
        Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cascadia Mono", 1, 28)); // NOI18N
        jLabel1.setText("Agencia De Viajes");
        Titulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 300, -1));

        fondoP.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 110));

        cboSeleccion.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        cboSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Montaña", "Playa" }));
        cboSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeleccionActionPerformed(evt);
            }
        });
        fondoP.add(cboSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 160, 40));

        MontañaP.setBackground(new java.awt.Color(255, 255, 255));
        MontañaP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MontañaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCostoGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoGuiaActionPerformed(evt);
            }
        });
        MontañaP.add(txtCostoGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 140, -1));

        jLabel5.setText("Costo Guia:");
        MontañaP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel6.setText("AlquilerEquipo");
        MontañaP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txtAlquilerEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlquilerEquipoActionPerformed(evt);
            }
        });
        MontañaP.add(txtAlquilerEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        jLabel7.setText("Seguro Porcentaje");
        MontañaP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        txtSeguroPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeguroPorcentajeActionPerformed(evt);
            }
        });
        MontañaP.add(txtSeguroPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 140, -1));

        fondoP.add(MontañaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 370, 500));

        PlayaP.setBackground(new java.awt.Color(255, 255, 255));
        PlayaP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PlayaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Impuesto Turistico");
        PlayaP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        txtImpuestoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImpuestoTuristicoActionPerformed(evt);
            }
        });
        PlayaP.add(txtImpuestoTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 140, -1));

        jLabel10.setText("Descuento Turistico");
        PlayaP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        txtDescuentoTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoTuristicoActionPerformed(evt);
            }
        });
        PlayaP.add(txtDescuentoTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 140, -1));

        fondoP.add(PlayaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 370, 500));

        txtHistorial.setColumns(20);
        txtHistorial.setRows(5);
        jScrollPane1.setViewportView(txtHistorial);

        fondoP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 320, 560));
        fondoP.add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        jLabel2.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel2.setText("Lugar");
        fondoP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel3.setText("Dias");
        fondoP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));
        fondoP.add(txtDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, -1));

        jLabel4.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        jLabel4.setText("Precio Base");
        fondoP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        fondoP.add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, -1));

        btnSalir.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        fondoP.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        fondoP.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        btnCalcular.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        fondoP.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 130, -1));

        getContentPane().add(fondoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeleccionActionPerformed
        int indexSeleccion = cboSeleccion.getSelectedIndex();
	if(indexSeleccion == 1){
	    MontañaP.setVisible(true);
	    PlayaP.setVisible(false);
            txtDestino.setEnabled(true);
            txtDias.setEnabled(true);
            txtPrecioBase.setEnabled(true);
	}
	else if(indexSeleccion == 2){
	    PlayaP.setVisible(true);
	    MontañaP.setVisible(false);
            txtDestino.setEnabled(true);
            txtDias.setEnabled(true);
            txtPrecioBase.setEnabled(true);
	}
	else if(indexSeleccion == 0){
	    MontañaP.setVisible(false);
	    PlayaP.setVisible(false);
            txtDestino.setEnabled(false);
            txtDias.setEnabled(false);
            txtPrecioBase.setEnabled(false);
	}
    }//GEN-LAST:event_cboSeleccionActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
	if(txtDestino.getText().trim().isEmpty() || txtDias.getText().trim().isEmpty() || txtPrecioBase.getText().trim().isEmpty()){
	    JOptionPane.showMessageDialog(this, "Error: Los Campos De Texto No Pueden Estar Vacios", "ERROR", JOptionPane.ERROR_MESSAGE);
	    return;
	}
	
		
	String destino = txtDestino.getText();
	int dias = Integer.parseInt(txtDias.getText());
	double precioBase = Double.parseDouble(txtPrecioBase.getText());
	
	String tipoViaje = (String) cboSeleccion.getSelectedItem();
	
	if(("Montaña").equals(tipoViaje)){
	    if(txtCostoGuia.getText().trim().isEmpty() || txtAlquilerEquipo.getText().trim().isEmpty() || txtSeguroPorcentaje.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, "No Puede Estar Vacio Los Campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            double costoGuia = Double.parseDouble(txtCostoGuia.getText());
            double alquilerEquipo = Double.parseDouble(txtAlquilerEquipo.getText());
            double seguroPorcentaje = Double.parseDouble(txtSeguroPorcentaje.getText());
            
            Montana montana = new Montana();
            
            montana.setDestino(destino);
            montana.setDias(dias);
            montana.setPrecioBase(precioBase);
            montana.setCostoGuia(costoGuia);
            montana.setAlquilerEquipo(alquilerEquipo);
            montana.setSeguroPorcentaje(seguroPorcentaje);
            
	}
	
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAlquilerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlquilerEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlquilerEquipoActionPerformed

    private void txtCostoGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoGuiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoGuiaActionPerformed

    private void txtSeguroPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeguroPorcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeguroPorcentajeActionPerformed

    private void txtImpuestoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImpuestoTuristicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImpuestoTuristicoActionPerformed

    private void txtDescuentoTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoTuristicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoTuristicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MontañaP;
    private javax.swing.JPanel PlayaP;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboSeleccion;
    private javax.swing.JPanel fondoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAlquilerEquipo;
    private javax.swing.JTextField txtCostoGuia;
    private javax.swing.JTextField txtDescuentoTuristico;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextArea txtHistorial;
    private javax.swing.JTextField txtImpuestoTuristico;
    private javax.swing.JTextField txtPrecioBase;
    private javax.swing.JTextField txtSeguroPorcentaje;
    // End of variables declaration//GEN-END:variables
}
